# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalculateDistance
                                 A QGIS plugin
 This plugin calculates the distances between end points of the lines or the distance between the closest and the furthest points in a point set.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-24
        copyright            : (C) 2021 by Hacettepe University
        email                : Hacettepe University
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CalculateDistance class from file CalculateDistance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .calculate_distance import CalculateDistance
    return CalculateDistance(iface)
